Feedback dari anda diperlukan! bantu kami dalam [meningkatkan modul ini](https://forms.gle/pWJd6y4hY4KWMcno6).

# Matriks, Sistem Persamaan Linear, dan Sistem Persamaan Non-Linear

## Daftar Isi

* Metode Penyelesaian Persamaan Linear
    * Penyulihan Maju/Mundur
    * Eliminasi Gauss
    * Modifikasi Eliminasi Gauss dengan Penumpuan
    * Modifikasi Eliminasi Gauss untuk Matriks Tridiagonal
* Perhitungan Determinan Matriks
* Perhitungan Invers Matriks
* Dekomposisi Matriks (LU)
* Metode Iterasi Menyelesaikan SPL
    * Gauss
    * Gauss-Seidel
* Metode Iterasi Menyelesai SPNL

## Metode Penyelesaian Persamaan Linear

Bentuk umum dari Sistem Persamaan Linear (SPL) yang terdiri dari $n$ persamaan dengan $n$ variabel bebas adalah:

$$
a_{11}x_1 + a_{12}x_2 + a_{13}x_3 + \dots + a_{1n}x_n = b_1 \\
a_{21}x_1 + a_{22}x_2 + a_{23}x_3 + \dots + a_{2n}x_n = b_2 \\
\vdots \\
a_{n1}x_1 + a_{n2}x_2 + a_{n3}x_3 + \dots + a_{3n}x_n = b_n \\
$$

SPL tersebut dapat dituliskan dalam bentuk matriks, dengan matriks koefisien dan matriks lengkapnya dituliskan secara berturut-turut sebagai berikut.

$$
\begin{bmatrix}
a_{11} && a_{12} && a_{13} && \dots && a_{1n} && b_1 \\
a_{21} && a_{22} && a_{23} && \dots && a_{2n} && b_2 \\
\vdots && && && && && \vdots\\
a_{n1} && a_{n2} && a_{n3} && \dots && a_{nn} && b_n \\
\end{bmatrix}
$$



Untuk menentukan solusi dari suatu SPL secara analitik, dapat dilakukan dengan metode Operasi Baris Elementer (OBE). OBE dilakukan dengan menyelesaikan matriks lengkap dari SPL dengan cara:
1. Menukarkan dua buah baris
2. Mengalikan suatu baris dengan suatu konstanta tak nol
3. Menambahkan k kali baris ke-i pada baris ke-j.

OBE tidak akan mengubah penyelesaian SPL. Namun, secara analitik OBE hanya dapat dilakukan untuk SPL yang sederhana, yaitu SPL yang memiliki matriks lengkap berukuran relatif kecil. Untuk SPL yang lebih rumit dengan matriks lengkap berukuran relatif besar, diperlukan metode penyelesaian secara numerik.

### Metode Penyulihan Maju/Mundur
Metode Penyulihan Maju dan Mundur. Suatu SPL yang matriks koefisiennya berbentuk matriks segitiga atas atau bawah dapat diselesaikan dengan metode penyulihan mundur atau maju. Matriks segitiga atas diselesaikan dengan metode penyulihan mundur, sedangkan matriks segitiga bawah diselesaikan dengan metode penyulihan maju.
$$
\begin{bmatrix}
3 && 2 &&   5 &&   7 \\
  && 7 &&  10 &&   2 \\
  &&   && -22 && -24 \\
  &&   &&     &&  45 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{bmatrix}
\begin{bmatrix}
41 \\ 37 \\ -136 \\ 90
\end{bmatrix}
$$

$$
\begin{bmatrix}
 45 &&     &&   &&   \\
-22 && -24 &&   &&   \\
  7 &&  10 && 2 &&   \\
  3 &&   2 && 5 && 7 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{bmatrix}
\begin{bmatrix}
90 \\ -136 \\ 37 \\ 41 \\  
\end{bmatrix}
$$

untuk mendapatkan solusi dari matriks segitiga atas, secara berurutan kita menyelesaikan:

$$
\begin{align}
x_n     & = \frac{1}{a_{n,n}} b_n \\
x_{n-1} & = \frac{1}{a_{n-1, n-1}} (b_{n-1} - a_{n-1, n} x_n) \\
x_{n-2} & = \frac{1}{a_{n-2, n-2}} (b_{n-2} - a_{n-2, n-1}x_{n-1} - a_{n-2, n}x_n) \\
\vdots\\
x_k     & = \frac{1}{a_{k,k}} (b_k - \sum_{i=k+1}^n a_{k,i} x_i) \\
\vdots\\
x_1     & = \frac{1}{a_{1,1}} (b_1 - \sum_{i=2}^n a_{k,i} x_i) \\
\end{align}
$$

metode ini disebut **penyulihan mundur (*back substitution*)** karena kita mencari solusi $x_i$ dari indeks $x_n$ dan secara iteratif 'mundur' ke $x_1$

In [1]:
% Penyulihan Mundur

% Masukan
n = 5;                             % ukuran SPL segitiga atas 
A = triu(randi([-10, 10], n, n+1)) % matriks SPL ekspansi dari Ax=b

K = A;   % untuk pengecekan solusi 

% Keluaran
x = zeros(1, n);                   % solusi SPL

% Algoritma

% pengecekan elemen diagonal matriks
start_process = true;
for k=n:-1:1
    if abs(A(k,k)) < 10^(-15)
        printf('proses gagal: pembagian oleh nol\n')
        start_process = false; 
        break
    end
end

% mulai penyulihan
if start_process
    x(n) = A(n, n+1) / A(n, n);
    
    for k=n-1:-1:1
        s = dot(A(k, (k+1):n), x(k+1:n));
        x(k) = (A(k, n+1) - s)/ A(k,k);
    end
end

x

A =

  -7  -9  -1  -7  -2  -3
   0  -2  -4   5   6   2
   0   0   8  -3   6   2
   0   0   0   2   2   9
   0   0   0   0  -8   4

x =

  -11.21429    5.00000    2.50000    5.00000   -0.50000



kita dapat membandingkan solusi dengan bentuk eselon reduksi (*reduced row echelon form*) dari matriks A,

In [2]:
% ingat K = A
K
rref(K)

K =

  -7  -9  -1  -7  -2  -3
   0  -2  -4   5   6   2
   0   0   8  -3   6   2
   0   0   0   2   2   9
   0   0   0   0  -8   4

ans =

    1.00000    0.00000    0.00000    0.00000    0.00000  -11.21429
    0.00000    1.00000    0.00000    0.00000    0.00000    5.00000
    0.00000    0.00000    1.00000    0.00000    0.00000    2.50000
    0.00000    0.00000    0.00000    1.00000    0.00000    5.00000
    0.00000    0.00000    0.00000    0.00000    1.00000   -0.50000



### Metode Eliminasi Gauss
Metode ini terdiri dari dua langkah besar, yaitu:
1. Mengubah SPL semula menjadi SPL segitiga atas melalui serangkaian operasi baris elementer (OBE).
2. Menyelesaikan SPL segitiga atas yang terbentuk dengan menggunakan penyulihan mundur.

In [19]:
% Eliminasi Gauss

% Masukan
n = 5;                             % ukuran matriks 
A = randi([-10, 10], n, n+1)       % matriks ekspansi Ax=b, yakni [A b]

K = A;   % untuk pengecekan solusi 

% Keluaran
x = zeros(1, n);                   % solusi SPL

% Algoritma

% pengecekan elemen diagonal matriks
start_process = true;
for i=n:-1:1
    if abs(A(i,i)) < 10^(-15)
        printf('proses gagal: pembagian oleh nol\n')
        start_process = false; 
        break
    end
end

if start_process
    
    % mulai eliminasi
    for k=1:n-1
        for i=(k+1):n
            p = A(i, k)/A(k, k);
            A(i, :) = A(i, :) - p * A(k, :);
        end
        
    end

    % mulai penyulihan
    x(n) = A(n, n+1) / A(n, n);
    for k=n-1:-1:1
        s = dot(A(k, (k+1):n), x(k+1:n));
        x(k) = (A(k, n+1) - s)/ A(k,k);
    end
end

x

A =

    9    8    3   -9   -6   -1
   -2    5    9   -4   -6    3
   -5   -1   -5    1   -4  -10
    9   -5    2    7   -1  -10
  -10    3    4   -9    4   10

x =

  -0.34201   3.06881   0.44686   1.35262   1.93989



In [20]:
% membandingkan dengan bentuk RREF dari ekspansi Ax = b
rref(K)

ans =

   1.00000   0.00000   0.00000   0.00000   0.00000  -0.34201
   0.00000   1.00000   0.00000   0.00000   0.00000   3.06881
   0.00000   0.00000   1.00000   0.00000   0.00000   0.44686
   0.00000   0.00000   0.00000   1.00000   0.00000   1.35262
   0.00000   0.00000   0.00000   0.00000   1.00000   1.93989



### Metode Penumpuan pada Eliminasi Gauss
Teknik penumpuan dilakukan dengan melakukan pertukaran baris pada matriks lengkap SPL. Hal ini dilakukan karena pertimbangan:
* Proses eliminasi Gauss gagal karena elemen penumpu bernilai nol.
* Adanya perambatan galat pembulatan yang besar.
* Hasil sensitif terhadap perubahan kecil pada konstanta pada sistem persamaan.

Untuk teknik penumpuan parsial, elemen penumpunya diambil dari $$\max_{k\leq i\leq n} |a_{i,k}|$$ Sedangkan, untuk teknik penumpuan total, elemen penumpunya diambil dari $$\max_{k\leq i, j\leq n} |a_{i,j}|$$

Setelah elemen penumpu dipilih, kita harus menempatkannya pada posisi $(k,k)$ dari matriks lengkap SPL.

In [5]:
% Eliminasi Gauss dengan Penumpuan Parsial

% Masukan
n = 5;                             % ukuran matriks 
A = randi([-10, 10], n, n+1)       % matriks ekspansi Ax=b, yakni [A b]

K = A;   % untuk pengecekan solusi 

% Keluaran
x = zeros(1, n);                   % solusi SPL

% Algoritma
start_process = true;

for k=1:(n-1)
    % cari baris untuk pivot
    [val, pivot] = max(abs(A(k:n, k)));

    if abs(val) < 10^(-15)
        printf('proses gagal: tidak ada elemen pivot yang tak nol\n')
        start_process = false;
        break
    end
    
    % tukar posisi
    temp            = A(k, :);
    A(k, :)         = A(k-1+pivot, :);
    A(k-1+pivot, :) = temp;
    
    % mulai eliminasi
    for i=(k+1):n
        p = A(i, k)/A(k, k);
        A(i, :) = A(i, :) - p * A(k, :);
    end
end

if start_process
    % mulai penyulihan
    x(n) = A(n, n+1) / A(n, n);
    for k=n-1:-1:1
        s = dot(A(k, (k+1):n), x(k+1:n));
        x(k) = (A(k, n+1) - s)/ A(k,k);
    end
end
x

A =

   -5    0    3   -2   -7   -6
   -6    1    9    2   -2   10
   -1   -8   -4  -10  -10   -6
  -10   -4    1    8    9   -4
   -8    0    6    4   10  -10

x =

   3.3324  -3.3147   2.7661   3.0097  -1.1976



### Modifikasi Eliminasi Gauss untuk SPL Tridiagonal

Bila kita memiliki SPL tridiagonal seperti matriks A di bawah, metode penyimpanan dalam bentuk matriks lengkap tidak akan efektif. Hal ini karena akan banyak memori yang terbuang hanya untuk menyimpan nilai nol. 

In [6]:
n = 10;
A = randi([-100 100], n, n);
A = triu(triu(A, -1)', -1);    % buat menjadi matriks tridiagonal
b = randi([-10 10], n, 1);

[A b]

ans =

  -91  -72    0    0    0    0    0    0    0    0    7
    7   -5   29    0    0    0    0    0    0    0   -6
    0  -17  -59   53    0    0    0    0    0    0   -7
    0    0   26  -14  -61    0    0    0    0    0   -6
    0    0    0  -71   58   35    0    0    0    0   -5
    0    0    0    0  -70   78   96    0    0    0    2
    0    0    0    0    0    1  -95   15    0    0   10
    0    0    0    0    0    0  -35  -83    6    0    4
    0    0    0    0    0    0    0   53  -13   48   10
    0    0    0    0    0    0    0    0   61   37    4



Karena itu, umumnya matriks A disimpan dalam bentuk tiga vektor

In [7]:
a = zeros(1, n);
d = zeros(1, n);
c = zeros(1, n);

d(n) = A(n, n);
for k = 1:n-1
    a(k+1) = A(k+1, k);
    d(k)   = A(k,   k);
    c(k)   = A(k, k+1);
end

[a' d' c' b]

ans =

    0  -91  -72    7
    7   -5   29   -6
  -17  -59   53   -7
   26  -14  -61   -6
  -71   58   35   -5
  -70   78   96    2
    1  -95   15   10
  -35  -83    6    4
   53  -13   48   10
   61   37    0    4



In [8]:
% Eliminasi Gauss untuk SPL Tridiagonal

% Masukan
n;               % ukuran matriks
a; d; c;         % vektor dari tridiagonal SPL
v = b;           % untuk pengecekan

% Keluaran
x = zeros(1, n);  % solusi SPL

% Algoritma

% cek penumpu
if min(abs(d)) < 10^(-15)
    printf('proses gagal: penumpu bernilai nol')
else
    % Gauss
    for k=1:n-1
        p = a(k+1)/d(k);
        d(k+1) = d(k+1) - p*c(k);
        b(k+1) = b(k+1) - p*b(k);
        a(k+1) = 0;
    end

    % Penyulihan mundur
    x(n) = b(n)/d(n);
    for k=(n-1):-1:1
        x(k) = (b(k) - c(k)*x(k+1))/d(k);
    end

end

x'

ans =

  -0.7287473
   0.8238334
   0.1110482
   0.2557927
   0.0869862
   0.2318881
  -0.1041483
  -0.0083986
  -0.0570460
   0.2021568



In [9]:
rref([A v])(:,n+1)

ans =

  -0.7287473
   0.8238334
   0.1110482
   0.2557927
   0.0869862
   0.2318881
  -0.1041483
  -0.0083986
  -0.0570460
   0.2021568



## Perhitungan Determinan
Untuk melakukan perhitungan determinan terhadap matriks $A$, kita cukup mengubahnya menjadi matriks segitiga atas $B$. Beberapa hal perlu diperhatikan pada saat melakukan proses OBE, yaitu:
1. Penukaran dua buah baris akan membuat nilai determinan matriks yang baru merupakan negatif dari determinan matriks semula.
2. Bila suatu baris dikali dengan konstanta $k$ maka nilai determinannya menjadi $k$ kali nilai determinan matriks semula.
3. Bila suatu baris ditambah dengan $k$ kali baris yang lain, nilai determinannya tidak berubah.

Selanjutnya, $$\det(B) = \prod_{i=1}^n a_{ii}$$

## Perhitungan Invers Matriks
Invers dari sebuah matriks $A$ dapat dicari dengan mengubah bentuk matriks ekspansi $$[A\,I]$$ menjadi bentuk $$[I\,B]$$Dengan demikian, matriks $B$ adalah invers dari matriks $A$. Proses pengubahan matriks $A$ menjadi $I$ dapat dilakukan lewat metode Gauss-Jordan

In [10]:
% Eliminasi Gauss-Jordan

% Masukan
n = 5;                             % ukuran matriks 
A = randi([-10, 10], n, n);        % matriks A
M = [A eye(n, n)];                 % matriks ekspansi [A I]

% Keluaran
B = zeros(n, n);                   % invers matriks A

% Algoritma

% pengecekan elemen diagonal matriks
start_process = true;
for i=n:-1:1
    if abs(M(i,i)) < 10^(-15)
        printf('proses gagal: pembagian oleh nol\n')
        start_process = false; 
        break
    end
end

if start_process
    % Gauss
    for k=1:n-1
        for i=(k+1):n
            p = M(i, k)/M(k, k);
            M(i, :) = M(i, :) - p * M(k, :);
        end       
    end
    
    % Jordan
    for k=n:-1:1
        for i=(k-1):-1:1
            p = M(i, k)/M(k, k);
            M(i, :) = M(i, :) - p * M(k, :);
        end
        
        M(k, :) = M(k, :)/ M(k,k);
    end
    
    B = M(:, n+1:2*n)
end

B =

   0.0207443  -0.1356266  -0.0077855  -0.0081247   0.0231020
   0.0124104  -0.0560644   0.0493080  -0.0727266   0.0105502
   0.0138917   0.1577448  -0.0354671   0.0174537  -0.1039080
  -0.0608137   0.0391931  -0.0311419   0.0916842  -0.0644548
  -0.0452484   0.0262795  -0.0631488  -0.0027195  -0.0152317



In [11]:
%mengecek selisih A*B dengan matriks identitas 
I = eye(n, n);
norm(A*B - I)

ans =    6.5234e-16


## Dekomposisi Matriks
Metode dekomposisi matriks digunakan untuk memfaktorkan suatu matriks atas faktor matriks segitiga atas dan matriks segitiga bawah. Tidak semua matriks dapat didekomposisi menjadi bentuk ini (kecuali dalam kita diperbolehkan menukar urutan kolom dari matriks terlebih dahulu). Pada kasus matriks yang dapat didekomposisi, solusi matriks segitiga atas dan matriks segitiga bawah yang didapat umumnya tidak tunggal. Jika dekomposisi dari matriks ditemukan, langkah untuk mencari penyelesaian SPL dengan metode dekomposisi adalah sebagai berikut:
$$A\overline{x} = \overline{b} \\
(LU)\overline{x} =\overline{b} \\
L(U\overline{x}) = \overline{b} \\
$$

Misalkan $\overline{y} = U\overline{x}$. Kita selesaikan SPL segitiga bawah $L\overline{y} = \overline{b}$ dengan penyulihan maju. Setelah vektor $\overline{y}$ diperoleh selanjutnya vektor $\overline{x}$ dapat dicari dari persamaan $U\overline{x} = \overline{y}$ dengan memakai penyulihan mundur. 

### Dekomposisi Doolitle
Pada dekomposisi Doolitle, elemen diagonal dari matriks segitiga bawah dipilih bernilai 1

In [12]:
n = 4;
A = randi([-10, 10], n, n)
L = eye(n, n);
U = zeros(n, n);

for i=1:n
    for k=i:n
        U(i, k) = A(i, k) - dot(L(i, 1:i), U(1:i, k));
    end
    U % untuk melihat proses
    
    for k=(i+1):n
        L(k, i) = (A(k, i) - dot(L(k, 1:i), U(1:i, i)))/ U(i, i);
    end
    L % untuk melihat proses
end

A =

   -4    9   -5   -2
   -3   -4   -9  -10
    0   10    2   -5
   -4    4    4  -10

U =

  -4   9  -5  -2
   0   0   0   0
   0   0   0   0
   0   0   0   0

L =

   1.00000   0.00000   0.00000   0.00000
   0.75000   1.00000   0.00000   0.00000
  -0.00000   0.00000   1.00000   0.00000
   1.00000   0.00000   0.00000   1.00000

U =

   -4.00000    9.00000   -5.00000   -2.00000
    0.00000  -10.75000   -5.25000   -8.50000
    0.00000    0.00000    0.00000    0.00000
    0.00000    0.00000    0.00000    0.00000

L =

   1.00000   0.00000   0.00000   0.00000
   0.75000   1.00000   0.00000   0.00000
  -0.00000  -0.93023   1.00000   0.00000
   1.00000   0.46512   0.00000   1.00000

U =

   -4.00000    9.00000   -5.00000   -2.00000
    0.00000  -10.75000   -5.25000   -8.50000
    0.00000    0.00000   -2.88372  -12.90698
    0.00000    0.00000    0.00000    0.00000

L =

   1.00000   0.00000   0.00000   0.00000
   0.75000   1.00000   0.00000   0.00000
  -0.00000  -0.93023   1.00000   0.00

In [13]:
% mengecek error sebagai selisih matriks L*U dan matriks A
norm(L*U-A)

ans =    8.8818e-16


## Metode Iterasi Untuk Menyelesaikan SPL

### Metode Jacobi

Metode iterasi Jacobi umumnya dipakai dalam pertimbangan:
* **Dapat ditebak nilai dari solusi eksaknya**, sehingga kita membutuhkan cara 'menggeser' tebakan awal ke solusi eksak.
* **Dimensi dari sistem persamaan besar**. Walau liminasi Gauss memastikan solusi tepat dari sistem persamaan, cara ini kurang/tidak feasible untuk matriks yang berukuran besar, misal 1000x1000. Sayangnya, permasalahan dalam kehidupan nyata biasanya menghasilkan bentuk matriks yang besar.
* **sistem persamaan *sparse* dan *diagonally dominated*.**


Matriks koefisien $A$ pada persamaan $$Ax = b$$ dapat didekomposisi menjadi matriks diagonal $D$, matriks segitiga atas *strict* $U$, dan matriks segitiga bawah *strict* $L$. [Strict dalam arti, diagonal dari matriks segitiga bernilai nol]. Dengan kata lain,

$$A = D+U+L = 
\begin{bmatrix}
a_{11} & 0 & \cdots & 0 \\
0 & a_{22} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & a_{nn} 
\end{bmatrix} + 
\begin{bmatrix}
0 & a_{12} & \cdots & a_{1n} \\
0 & 0 & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & 0
\end{bmatrix} +
\begin{bmatrix}
0 & 0 & \cdots & 0 \\
a_{21} & 0 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & 0
\end{bmatrix}.
$$

Sehingga
$$
\begin{align}
Ax &= b \\
(D+U+L)x &= b\\
Dx &= b - (U+L)x \\
x &= D^{-1} (b - (U+L)x) \\
\end{align}
$$

Misalkan $R=U+L$. Solusi dari sistem persamaan $Ax = b$ dapat ditentukan secara iteratif dengan
$$ x^{(k+1)} = D^{-1} (b - R x^{(k)}) $$

dimana $x^{(k)}$ adalah aproksimasi ke-*k* dari $x$. Rumus iterasi Metode Jacobi versi elemen matriks adalah
$$x^{(k+1)}_i := \frac{1}{a_{ii}}\Big(b_i - \sum_{j=1, j\neq i}^n a_{ij}x^{(k)}_j \Big)$$

dengan kriteria penghentian iterasi yaitu:
$$\max_{1\leq i\leq n} \frac{|x^{k+1}_i − x^k_i|}{|x^{k+1}_i|} < \epsilon $$

In [14]:
% Algoritma

% Masukan
n = 4;                   % ukuran matriks
A = [10 -1  2  0;
     -1 11 -1  3;
      2 -1 10 -1;
      0  3 -1  8];
b = [6 25 -11 15]';
eps = 10^-8;

% Keluaran
x = zeros(n, 1);

% Algoritma
x_old = zeros(n, 1);
D = diag(diag(A));
R = A-D;

for iteration = 1:1000
    x = D\(b - R*x);
    if norm(x_old - x) < eps
        break
    else
        x_old = x;
    end
end

% Keluaran
x

x =

   1.00000
   2.00000
  -1.00000
   1.00000



In [15]:
A*x - b

ans =

   1.1958e-08
  -2.2090e-08
   1.5531e-08
  -1.7699e-08



### Metode Gauss-Seidel

Perhatikan pada metode Gauss, jika kita telah menghitung nilai $x^{(k+1)}_1$ sampai dengan $x^{(k+1)}_i$, kita tetap harus menghitung nilai $x^{(k+1)}_{i+1}$ berdasarkan nilai $x^{k}_{j\neq i+1}$. Padahal nilai $x_1$ sampai dengan $x_i$ sudah 'dalam keadaan yang mengkilat'. Metode Gauss-Seidel mencoba mempercepat laju kekonvergenan metode Gauss atas pertimbangan ini. Menggunakan dekomposisi pada metode Gauss sebelumnya, secara analitik metode Gauss-Seidel sebagai berikut:

$$
\begin{align}
Ax &= b \\
(D+U+L)x &= b\\
(D+L)x &= b - (U)x \\
x &= (D+L)^{-1} (b - Ux) \\
\end{align}
$$

Secara umum, rumus iterasi metode Gauss Seidel adalah
$$x^{k+1}_i := \frac{1}{a_{ii}} \Big(b_i - \sum^{i−1}_{j=1} a_{ij}x^{k+1}_j + \sum^n_{j=i+1} a_{ij}x^k_j \Big) $$

dengan kriteria penghentian iterasi:
$$ \max_{1\leq i \leq n} \frac{|x^{k+1}_i − x^k_i|}{|x^{k+1}_i|} < \epsilon $$

In [16]:
% Algoritma

% Masukan
n = 4;                   % ukuran matriks
A = [10 -1  2  0;
     -1 11 -1  3;
      2 -1 10 -1;
      0  3 -1  8];
b = [6 25 -11 15]';
eps = 10^-8;

% Keluaran
x = zeros(n, 1);

% Algoritma
x_old = zeros(n, 1);
L = tril(A);              % matriks segitiga bawah
U = triu(A, 1);           % matriks segitiga atas strict

for iteration = 1:1000
    x = L\(b - U*x);
    if norm(x_old - x) < eps
        break
    else
        x_old = x;
    end
end

% Keluaran
x

x =

   1.00000
   2.00000
  -1.00000
   1.00000



In [17]:
A*x-b

ans =

   5.5764e-11
  -1.3883e-09
   2.9453e-10
   0.0000e+00

